### ISSUE TITLE
iOS 16.4 Phone Number validation all returns False.

### ISSUE THREAD

**Issue by yacoublambaz** [flutter-form-builder-ecosystem/phone_number#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

latest

### Flutter doctor

[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3.1 22E261 darwin-arm64 (Rosetta), locale en-JO)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Connected device (3 available)
    ! Error: Luai’s Apple Watch needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)
[✓] HTTP Host Availability

### Minimal code example

        print(await PhoneNumberUtil().validate("+962798628842"));
        print(await PhoneNumberUtil().validate("+14175555470"));
#return false even though both are valid.

### Current Behavior

Both return false even though they should return true.

### Expected Behavior

They should return true

### Steps To Reproduce

Run the code in any iOS 16.4 mobile.

### Aditional information

.

**Comment by deandreamatias** [comment]
Do you use the last version on main branch?

**Comment by yacoublambaz** [comment]
Fixed by upgrading to latest version on main branch.
