### ISSUE TITLE
[Field name or General]: update dependency on PhoneNumberCoreKit to latest

### ISSUE THREAD

**Issue by rbarzel** [flutter-form-builder-ecosystem/phone_number#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

2.0.0

### What you'd like to happen

phone_number 2.0.0 depends on PhoneNumberKit 3.5.8

My app uses flutter_libphonenumber and I'm presently unable to build with the latest version of either plugin because flutter_libphonenumber depends on PhoneNumberKit 3.5.10. 

It would be great if phone_number was updated to depend on the latest PhoneNumberKit to avoid this conflict.

Thanks!

**Comment by pavlouha** [comment]
same problem

**Comment by dmiedev** [comment]
<img width="826" alt="Snímek obrazovky 2023-06-08 v 17 27 04" src="https://github.com/flutter-form-builder-ecosystem/phone_number/assets/40038420/52674ae1-f7ca-4104-9151-f693d2623ff8">
Have you completed the setup step?

**Comment by pavlouha** [comment]
<img width="625" alt="image" src="https://github.com/flutter-form-builder-ecosystem/phone_number/assets/28784325/008adf99-f0a0-4243-8417-720b76e61b47">
Yes, our problem is that flutter_libphonenumber uses 3.5.10 instead of 3.5.8

**Comment by kyeshmz** [comment]
It seems like that the update process failed for the most recent 2.0.0, although the podspec in the github master is working.

This is a direct screenshot from when you download the tar.gz from https://pub.dev/packages/phone_number/versions.
We can see that its depending on 3.5.8 

It would be great if any of the members able to push the repository to pubdev be able to handle this, as it just seems like a push error @deandreamatias

<img width="876" alt="Screenshot 2023-06-15 at 9 45 55 AM" src="https://github.com/flutter-form-builder-ecosystem/phone_number/assets/12763472/c6649dcb-6341-40a5-8f42-5412540e3040">

**Comment by deandreamatias** [comment]
If someone can create a release PR like [this](https://github.com/flutter-form-builder-ecosystem/phone_number/pull/85/files), I should be merge and create a tag with new version.

- Update changelog
- Update version on pubspec (I thinks that a fix is enoght 2.0.1)
- Update (autogenerated files) dependencies lock files

**Comment by kyeshmz** [comment]
I don't think its the same, as there is nothing that requires a diff in the git changelog, just in pubspec.
But nevertheless, I can still make the PR
