### ISSUE TITLE
[Country Code]: PhoneNumber().parse always returns US on Canada number in Android. iOS working as expected. 

### ISSUE THREAD

**Issue by simranjeet09** [flutter-form-builder-ecosystem/phone_number#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

2.0.0

### Platforms

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

### Minimal code example

 PhoneNumberUtil plugin = PhoneNumberUtil();
    try {
      PhoneNumber phoneNumber = await plugin.parse("+14379720810" ); 
      countryCodeDefault = "+${phoneNumber.countryCode}";
      phoneEditingController.text = widget.initialVal?.substring(countryCodeDefault.length) ?? " ";
      print( phoneNumber.regionCod);
       }catch(e){}

### Current Behavior

await plugin.parse("+14379730810" );  always returns US as country 

### Expected Behavior

await plugin.parse("+14379720810" ); should returns CA 

### Steps To Reproduce

Try parsing +14379720810 on Android only. Ios works as expected

**Comment by VictorUvarov** [comment]
I would file the issue on the [libphonenumber](https://github.com/google/libphonenumber) since all the plugin does is call their API

**Comment by joshisijan** [comment]
![Screenshot 2023-08-08 at 11 17 14 AM](https://github.com/flutter-form-builder-ecosystem/phone_number/assets/33340684/164e4042-af81-4865-b314-beca74c63308)


From official java demo from libphonenumber the number parser gives 'CA' as regionCode. But through package the same phone number when parsed gives me 'US'.
link: https://libphonenumber.appspot.com
