### ISSUE TITLE
Issues with Determining the ISO3166 Country Code given a phone number, validation

### ISSUE THREAD

**Issue by ooglek** [flutter-form-builder-ecosystem/phone_number#64]
In our app I'm given a phone number. I don't know what country it is from, but we require the end user to enter the E164 +xxx country code.

With this library I cannot seem to turn a "+1 314 246 xxxx" phone number into the value "US" nor "+1 787 246 xxxx" into "PR"

Our customers are all over the world, and I don't want a "Country Code Picker" either. 

LibPhoneNumber can determine that the +1 314 246 xxxx is in the US, I'm not sure why this library does not expose it.

Help!

The big challenge here is that this library uses `isValidNumberForRegion()` as implemented in this library, in Java:

https://github.com/nashfive/phone_number/blob/d4ff262c4f91b2880f03a0d6072b5c7073772ad4/android/src/main/java/com/julienvignali/phone_number/PhoneNumberPlugin.java#L107

Now I have to know the region ahead of validation, but I don't know it, but it should be implied by the number, not requiring me to include the region. 

It would be nice to be able to have access to a different `.validate` function to match the Google LibPhoneNumber options, such as `.isPossibleNumber()` and `.isValidNumber()` rather than the very specific `.isValidNumberForRegion()`

Without this flexibility and access to the rest of the functionality of libphonenumber, I'm struggling to accomplish reliance on the value that LibPhoneNumber provides!

**Comment by ooglek** [comment]
At least for consistency with IOS, Android LibPhoneNumber should use `isValidNumber()` rather than `isValidNumberForRegion()`

**Comment by ooglek** [comment]
I guess the option here is to fork and modify myself? This is disappointing that there's no response from the developer in a month. I see that it is being updated with the latest dependencies, but frustrating that no actual code changes or improvements are occuring.

**Comment by ooglek** [comment]
@nashfive @deandreamatias @iamsahilsonawane Any chance you're willing to address this? I'm willing to make a pull request if you'll acknowledge it and review it and potentially accept it. I'm going to write the code either way.

**Comment by deandreamatias** [comment]
Hi @ooglek 
Sorry for delay answer. 
I can review your code if you open a pull request.

I don't have time to enter and learn how the code is implemented. The is the motive that I don't start to fix bugs and develop new features. Also I don't has a lot experience to flutter plugins.

In another way, I really sorry for problems that this bugs can will be cause, but remember that this plugin is open source and we don't  receive money to work in it.
I believe that all contributors has some priorities to solved before develop this plugin.

Take a look to this discussion that I started to solve this and other problems
https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/discussions/1038
