### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0. 

### ISSUE THREAD

**Issue by kaciula** [flutter-form-builder-ecosystem/phone_number#70]
## Environment

**Package version:**

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale en-RO)
    • Flutter version 3.0.1 at /Users/ka/dev/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (8 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ka/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (4 available)
    • iPhone (mobile)                     • b4edf88c07bc09f8c4aa16ca492b0ddbbc369aa1 • ios            • iOS 15.5 19F77
    • iPhone SE (3rd generation) (mobile) • 13CC9010-3592-4FC3-A31E-3B89FEE726F6     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                     • macos                                    • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)                        • chrome                                   • web-javascript • Google Chrome 103.0.5060.114
    ! Error: iPhone is busy: Fetching debug symbols for iPhone. Xcode will continue when iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details>
  <summary>Code sample</summary>

```
I cannot reproduce it but I am getting over 40 crash reports about this.
```

</details>

## Description

**Expected behavior:** Do not crash

**Current behavior:** Crash

## Steps to reproduce

I cannot reproduce it but I have over 40 crash resports about this.

## Stacktrace/Logcat 
0  ???                            0x0 _OneByteString.codeUnitAt (dart:core)
1  ???                            0x0 StringExt.findAdditionRange + 43 (utils.dart:43)
2  ???                            0x0 PhoneNumberEditingController._onStopFormatting + 185 (controller.dart:185)
3  ???                            0x0 PhoneNumberEditingController._formatAndSet + 145 (controller.dart:145)
4  ???                            0x0 PhoneNumberEditingController.value= + 89 (controller.dart:89)
5  ???                            0x0 EditableTextState._value= + 2211 (editable_text.dart:2211)
6  ???                            0x0 EditableTextState._formatAndSetValue + 2617 (editable_text.dart:2617)
7  ???                            0x0 EditableTextState.updateEditingValue + 1967 (editable_text.dart:1967)
8  ???                            0x0 TextInput._handleTextInputInvocation + 1730 (text_input.dart:1730)
9  ???                            0x0 MethodChannel._handleAsMethodCall + 404 (platform_channel.dart:404)
10 ???                            0x0 MethodChannel.setMethodCallHandler.<fn> + 397 (platform_channel.dart:397)
11 ???                            0x0 _DefaultBinaryMessenger.setMessageHandler.<fn> + 380 (binding.dart:380)
12 ???                            0x0 _DefaultBinaryMessenger.setMessageHandler.<fn> + 377 (binding.dart:377)

**Comment by iamsahilsonawane** [comment]
HIi @kaciula sorry for the late reply, the plugin maintenance was on pause. 

Are you still facing this issue? If yes, you said you cannot reproduce it, does it work on the local then?

**Comment by kaciula** [comment]
@deandreamatias The issue keeps showing up in the Firebase Crashlytics dashboard. I have 64 non-fatal crash reports for 40 users right now.

It works fine when I test it on various devices. I cannot reproduce this behavior locally.

**Comment by deandreamatias** [comment]
Without code sample and steps to reproduce bug, we cant help, sorry.
If will have more info, we will open this issue again
