### ISSUE TITLE
PR #73 causing failure in validate() on IOS

### ISSUE THREAD

**Issue by ooglek** [flutter-form-builder-ecosystem/phone_number#82]
## Description

Pull Request #73 which fixes Issue #64 on Android breaks IOS.

**Expected behavior:** validate() works on IOS when not specifying a regionCode to the dart lib, `region` to the IOS lib

**Current behavior:** validate() fails on IOS because it is checking to see if `region` is empty and throwing an exception if it is. Which it now can be in the dart lib.

## Steps to reproduce

1. Install the library main @ 688e85155106a505385cab7c010fe750c64d6d7b
2. Run `validate()` on IOS
3. See PlatformException thrown that 'string is empty' but it is really the region that is empty

https://github.com/flutter-form-builder-ecosystem/phone_number/blob/688e85155106a505385cab7c010fe750c64d6d7b/ios/Classes/SwiftPhoneNumberPlugin.swift#L26-L42

The `guard` section needs to allow region to be empty, and then `withRegion` needs to be optionally passed to `kit.isValidPhoneNumber()`

## Stacktrace/Logcat 

```
PlatformException(InvalidArgument, The 'string' argument is missing., null, null)
```

**Comment by iamsahilsonawane** [comment]
Hey @ooglek thanks for pointing it out. I'll fix this ASAP
