### ISSUE TITLE
Very confusing validate function

### ISSUE THREAD

**Issue by jerinho** [flutter-form-builder-ecosystem/phone_number#95]
Seriously I cannot think of any tiny good reason why you need to catch the exception for invalid output but at the same return a boolean to tell if the value is correct or not.

`bool isvalid = await PhoneNumberUtil().validate('...')`

> Unhandled Exception: PlatformException(InvalidNumber, Number ... is invalid, null, null)

**Comment by deandreamatias** [comment]
Keep calm jerinho
If you can fill the template with all info, we can help you
