### ISSUE TITLE
Invalid number with valid format in IOS

### ISSUE THREAD

**Issue by hasibul-hasan-shuvo** [flutter-form-builder-ecosystem/phone_number#97]
When trying to check phone number validation it returns invalid even in a valid format. It's having on IOS devices only and not on all IOS devices. I saw that the native package you are using is updated recently but you haven't updated the package version in your package. Hopefully, you will solve the issue as soon as possible.

**Comment by VictorUvarov** [comment]
I seem to also be getting some phone number parsing errors on valid numbers on a physical device and not the simulator...
It seems this iOS package depends on `PhoneNumberKit/PhoneNumberKitCore, 3.3.4`. What is the most recent version?

**Comment by hasibul-hasan-shuvo** [comment]
@VictorUvarov The latest version is 3.5.8.

**Comment by VictorUvarov** [comment]
@hasibul-hasan-shuvo It looks like the iOS library no longer supports a recent version on cocoapods. It suggests using the git dependency instead, since they most likely just support swift package manager now. Might need to update the pod spec file to use git instead.

**Comment by VictorUvarov** [comment]
Looks like PhoneNumberKit cocoapods is outdated. Here is the official cocopods version of PhoneNumberKit https://github.com/CocoaPods/Specs/tree/master/Specs/2/4/b/PhoneNumberKit

**Comment by deandreamatias** [comment]
Hi guys!
If someone of you can create a PR with this change, I can review and merge
Thanks for help
